[build]
  command = ""
  publish = "."


[[redirects]]
from = "/"
to = "/pages/en.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/pages/en.html"
status = 200

[[redirects]]
from = "/index-es.html"
to = "/pages/es.html"
status = 200

[[redirects]]
from = "/index-el.html"
to = "/pages/el.html"
status = 200

[[redirects]]
from = "/index-it.html"
to = "/pages/it.html"
status = 200

[[redirects]]
from = "/index-de.html"
to = "/pages/de.html"
status = 200

[[redirects]]
from = "/index-fr.html"
to = "/pages/fr.html"
status = 200

[[redirects]]
from = "/index-ru.html"
to = "/pages/ru.html"
status = 200

[[redirects]]
from = "/index-tr.html"
to = "/pages/tr.html"
status = 200

[[redirects]]
from = "/index-sv.html"
to = "/pages/sv.html"
status = 200

[[redirects]]
from = "/index-da.html"
to = "/pages/da.html"
status = 200

[[redirects]]
from = "/en"
to = "/pages/en.html"
status = 200

[[redirects]]
from = "/en/"
to = "/pages/en.html"
status = 200

[[redirects]]
from = "/en/*"
to = "/pages/en.html"
status = 200

[[redirects]]
from = "/es"
to = "/pages/es.html"
status = 200

[[redirects]]
from = "/es/"
to = "/pages/es.html"
status = 200

[[redirects]]
from = "/es/*"
to = "/pages/es.html"
status = 200

[[redirects]]
from = "/el"
to = "/pages/el.html"
status = 200

[[redirects]]
from = "/el/"
to = "/pages/el.html"
status = 200

[[redirects]]
from = "/el/*"
to = "/pages/el.html"
status = 200

[[redirects]]
from = "/it"
to = "/pages/it.html"
status = 200

[[redirects]]
from = "/it/"
to = "/pages/it.html"
status = 200

[[redirects]]
from = "/it/*"
to = "/pages/it.html"
status = 200

[[redirects]]
from = "/de"
to = "/pages/de.html"
status = 200

[[redirects]]
from = "/de/"
to = "/pages/de.html"
status = 200

[[redirects]]
from = "/de/*"
to = "/pages/de.html"
status = 200

[[redirects]]
from = "/fr"
to = "/pages/fr.html"
status = 200

[[redirects]]
from = "/fr/"
to = "/pages/fr.html"
status = 200

[[redirects]]
from = "/fr/*"
to = "/pages/fr.html"
status = 200

[[redirects]]
from = "/ru"
to = "/pages/ru.html"
status = 200

[[redirects]]
from = "/ru/"
to = "/pages/ru.html"
status = 200

[[redirects]]
from = "/ru/*"
to = "/pages/ru.html"
status = 200

[[redirects]]
from = "/tr"
to = "/pages/tr.html"
status = 200

[[redirects]]
from = "/tr/"
to = "/pages/tr.html"
status = 200

[[redirects]]
from = "/tr/*"
to = "/pages/tr.html"
status = 200

[[redirects]]
from = "/sv"
to = "/pages/sv.html"
status = 200

[[redirects]]
from = "/sv/"
to = "/pages/sv.html"
status = 200

[[redirects]]
from = "/sv/*"
to = "/pages/sv.html"
status = 200

[[redirects]]
from = "/da"
to = "/pages/da.html"
status = 200

[[redirects]]
from = "/da/"
to = "/pages/da.html"
status = 200

[[redirects]]
from = "/da/*"
to = "/pages/da.html"
status = 200

[[redirects]]
from = "/*"
to = "/pages/en.html"
status = 200
